### ISSUE TITLE
Image details are empty

### ISSUE THREAD

**Issue by atlochowski** [monich/harbour-foilpics#27]
Open app ->swipe to the left -> open image -> nchoose image details from pulley menu

`Dec 03 11:04:54 Sailfish [23496]: [W] unknown:26 - file:///usr/share/harbour-foilpics/qml/GalleryDetailsPage.qml:26: ReferenceError: FileUtil is not defined`

**Comment by monich** [comment]
Should be fixed by https://github.com/monich/harbour-foilpics/commit/ee58b1b, thanks for the report!

**Comment by monich** [comment]
Fixed in version [1.0.11](https://github.com/monich/harbour-foilpics/releases/tag/1.0.11)
