### ISSUE TITLE
CLI to decrypt

### ISSUE THREAD

**Issue by PrasannaVenkadesh** [monich/harbour-foilpics#30]
Hi. I was using FoilPics to encrypt images in my Sailfish phone. Unfortunately, I lost the display and I cannot see what's going on in the screen. Fortunately I can SSH into my phone and I got access to the private key which was stored in ~/.local/share/foil/foil.key as mentioned.

I also remember my password, I was looking for ways to decrypt the images. Is there a CLI to decrypt the images by providing the key, encrypted file and the password?

**Comment by monich** [comment]
Yes, there's a CLI tool for that, called `foilmsg`. It's not particularly user-friendly, but it can do what you need. You can build it yourself out of [these](https://github.com/monich/foil/tree/master/tools/foilmsg) sources, or there are prebuilt armv7hl rpms [here](https://build.sailfishos.org/package/show/home:slava:test/foil) if you want to run it on Sailfish OS phone.

Once you get the tool running, it goes like this:
```
$ file 34309C18ABE56470
34309C18ABE56470: data
$ foilmsg -v -d -s foil.key -P $PASSWORD -f 34309C18ABE56470 -o a.png
[foilmsg] Private key fingerprint: ee:cb:62:ca:2b:b5:fd:e5:55:1f:79:e0:40:c6:7b:9c
[foilmsg] Found 7 header(s)
[foilmsg]   Original-Path: /home/defaultuser/Pictures/Screenshots/Screenshot_20201224_003.png
[foilmsg]   Original-Size: 1550822
[foilmsg]   Title: Screenshot_20201224_003
[foilmsg]   Modification-Time: 2020-12-24T03:24:58.670780Z
[foilmsg]   Access-Time: 2020-12-24T03:24:57.535780Z
[foilmsg]   Orientation: 0
[foilmsg]   Image-Date: 2020-12-24T03:24:58Z
$ file a.png 
a.png: PNG image data, 1080 x 1920, 8-bit/color RGBA, non-interlaced
```
This particular example decrypts the file named `34309C18ABE56470`, writes the output to `a.png` and dumps the additional meta-information stored in the encrypted file.

**Comment by PrasannaVenkadesh** [comment]
@monich Thanks a lot for responding as soon as possible. This means a lot to me. I suggest, adding this info in FoilPics README as it might be helpful for people like me.

**Comment by PrasannaVenkadesh** [comment]
I was able to successfully build and decrypt the image! Thanks a ton, again!
