### ISSUE TITLE
Share via Bluetooth looks bad

### ISSUE THREAD

**Issue by atlochowski** [monich/harbour-foilpics#33]
Steps to reproduce:

Tap on photo -> Tap on Bluetooth -> List of available devices overlays Bluetooth and MMS icons but background is transparent, so it looks bad.

**Comment by atlochowski** [comment]
Jolla has redesigned sharing menu in the newest OS version.

**Comment by monich** [comment]
Yeah, I need to disable sharing for latest Sailfish OS like I already did for ofono/NFC loggers. Will do.

**Comment by monich** [comment]
Version 1.0.17 should behave better. It won't even show the sharing menu when in-app sharing is unavailable 😁

**Comment by atlochowski** [comment]
New Sharing API is available.

**Comment by monich** [comment]
> New Sharing API is available.

Yeah, I know. And there's still space for "Share" menu item in the pulley menu for the new out-of-process sharing. It's just a matter of adding it.

**Comment by monich** [comment]
Added in version 1.0.19, give it a try

**Comment by monich** [comment]
Fixed?

**Comment by atlochowski** [comment]
yes
